apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boradtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boradtest
    spec:
      containers:
      - name: boradtest
        image: nhjcontainreg.azurecr.io/boradtest:#{Build.BuildId}#
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: boradtest
spec:
  type: LoadBalancer
  ports:
  - port: 8089
  selector:
    app: boradtest
