apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mavenweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mavenweb
    spec:
      containers:
      - name: mavenweb
        image: nhjcontainreg.azurecr.io/mavenweb:#{Build.BuildId}#
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: mavenweb
spec:
  type: LoadBalancer
  ports:
  - port: 8089
  selector:
    app: mavenweb
